### ISSUE TITLE
How to get host "Private memory" counter?

### ISSUE THREAD

**Issue by leweafan** [dnaeon/py-vpoller#197] opened 2016-06-27 11:52 UTC
As I know Private =  Consumed - Overhead Consumption. How I can get **host** Private or Overhead Consumption memory counter?
There is mem.overhead.kiloBytes.average but it returns 0.
P.S. I'm using vSphere 6.0

**Comment by dnaeon** [comment] 2016-06-27 13:49
No troubles getting the `mem.overhead.kiloBytes.average` performance counter here.

Here's the command I'm using.

```bash
$ vpoller-client --method host.perf.metric.get --vsphere-host <vcenter-fdqn> --name <esxi-fdqn> --counter mem.overhead.kiloBytes.average --max-sample 3 | jq '.'
```

Which returns the following result.

```json
{
  "success": 0,
  "msg": "Successfully retrieved performance metrics",
  "result": [
    {
      "value": 967688,
      "counterId": "mem.overhead.kiloBytes.average",
      "interval": 20,
      "instance": "",
      "timestamp": "2016-06-27 14:31:00+00:00"
    },
    {
      "value": 967408,
      "counterId": "mem.overhead.kiloBytes.average",
      "interval": 20,
      "instance": "",
      "timestamp": "2016-06-27 14:31:20+00:00"
    },
    {
      "value": 967408,
      "counterId": "mem.overhead.kiloBytes.average",
      "interval": 20,
      "instance": "",
      "timestamp": "2016-06-27 14:31:40+00:00"
    }
  ]
}
```

You are using vSphere 6.0? Is that the vCenter and ESXi hosts version or both?

**Comment by leweafan** [comment] 2016-06-27 15:53
Yeah I'm using vSphere 6.0 (latest) with vcenter.
I'm using the same command and getting the following output 

```
{
  "msg": "Successfully retrieved performance metrics",
  "result": [
    {
      "timestamp": "2016-06-27 15:43:20+00:00",
      "counterId": "mem.overhead.kiloBytes.average",
      "interval": 20,
      "value": 0,
      "instance": ""
    },
    {
      "timestamp": "2016-06-27 15:43:40+00:00",
      "counterId": "mem.overhead.kiloBytes.average",
      "interval": 20,
      "value": 0,
      "instance": ""
    },
    {
      "timestamp": "2016-06-27 15:44:00+00:00",
      "counterId": "mem.overhead.kiloBytes.average",
      "interval": 20,
      "value": 0,
      "instance": ""
    }
  ],
  "success": 0
}
```
I have tested this command on two different installations and it's always 0.

**Comment by dnaeon** [comment] 2016-06-27 17:43
Is the actual value different when you check the vsphere client?

Do you have any 5.x hosts you can query as well?

**Comment by leweafan** [comment] 2016-06-28 09:17
It's definitely different.
Unfortunately I do not have 5.x hosts.

**Comment by dnaeon** [comment] 2016-07-01 18:15
Cannot reproduce this on a vCenter 6.x with connected ESXi 5.x hosts.

Will try to get an ESXi 6.x these days and see if I can reproduce this one. Could be related to ESXi 6.x, but still need to verify this.

**Comment by iamthemuffinman** [comment] 2016-11-23 22:17
@dnaeon Did you figure this one out?

**Comment by dnaeon** [comment] 2016-11-24 11:18
@iamthemuffinman no, not really. Unfortunately, I didn't find some spare time to troubleshoot this one. I'd appreciate any help if anyone can troubleshoot it.

**Comment by dnaeon** [comment] 2018-06-28 17:00
Closing issue, as I was not able to reproduce it.

**Closed by dnaeon** 2018-06-28 17:00 UTC
