### ISSUE TITLE
host unavailability cause whole vpoller-worker to fail

### ISSUE THREAD

**Issue by jabalv** [dnaeon/py-vpoller#194] opened 2016-06-22 11:49 UTC
When I monitor esxi hosts and one of them fails or become unreachable from worker logs:

> ERROR/VPollerWorker-1] Cannot connect to hostname: [Errno 110] Connection timed out

or

> Cannot connect to hostname: [Errno 113] No route to host

Then whole vpoller stops and do not perform any checks, but processes still show heatlhy status and are running. No more records in log files.

Errors messages:

> [2016-06-22 14:27:00,958 - WARNING/VPollerWorker-2] Task host.perf.metric.get failed: Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/vpoller/task/decorators.py", line 55, in wrapper
>     result = fn(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/vpoller/vsphere/tasks.py", line 1462, in host_perf_metric_get
>     obj_type=pyVmomi.vim.HostSystem
>   File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 412, in get_object_by_property
>     view_ref = self.get_container_view(obj_type=[obj_type])
>   File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 347, in get_container_view
>     container = self.si.content.rootFolder
>   File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 123, in si
>     self.connect()
>   File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 159, in connect
>     sslContext=self.ssl_context,
>   File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 786, in SmartConnect
>     sslContext)
>   File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 671, in __FindSupportedVersion
>     sslContext)
>   File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 591, in __GetServiceVersionDescription
>     path + "/vimServiceVersions.xml", sslContext)
>   File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 557, in __GetElementTree
>     conn.request("GET", path)
>   File "/usr/lib64/python2.7/httplib.py", line 979, in request
>     self._send_request(method, url, body, headers)
>   File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
>     self.endheaders(body)
>   File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib64/python2.7/httplib.py", line 835, in _send_output
>     self.send(msg)
>   File "/usr/lib64/python2.7/httplib.py", line 797, in send
>     self.connect()
>   File "/usr/lib64/python2.7/httplib.py", line 1189, in connect
>     HTTPConnection.connect(self)
>   File "/usr/lib64/python2.7/httplib.py", line 778, in connect
>     self.timeout, self.source_address)
>   File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
>     raise err
> error: [Errno 110] Connection timed out

> [2016-06-22 14:14:22,056 - WARNING/VPollerWorker-1] Task host.perf.metric.get failed: Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/vpoller/task/decorators.py", line 55, in wrapper
>     result = fn(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/vpoller/vsphere/tasks.py", line 1462, in host_perf_metric_get
>     obj_type=pyVmomi.vim.HostSystem
>   File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 412, in get_object_by_property
>     view_ref = self.get_container_view(obj_type=[obj_type])
>   File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 347, in get_container_view
>     container = self.si.content.rootFolder
>   File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 123, in si
>     self.connect()
>   File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 159, in connect
>     sslContext=self.ssl_context,
>   File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 786, in SmartConnect
>     sslContext)
>   File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 671, in __FindSupportedVersion
>     sslContext)
>   File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 591, in __GetServiceVersionDescription
>     path + "/vimServiceVersions.xml", sslContext)
>   File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 557, in __GetElementTree
>     conn.request("GET", path)
>   File "/usr/lib64/python2.7/httplib.py", line 979, in request
>     self._send_request(method, url, body, headers)
>   File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
>     self.endheaders(body)
>   File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib64/python2.7/httplib.py", line 835, in _send_output
>     self.send(msg)
>   File "/usr/lib64/python2.7/httplib.py", line 797, in send
>     self.connect()
>   File "/usr/lib64/python2.7/httplib.py", line 1189, in connect
>     HTTPConnection.connect(self)
>   File "/usr/lib64/python2.7/httplib.py", line 778, in connect
>     self.timeout, self.source_address)
>   File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
>     raise err
> error: [Errno 113] No route to host

I was able to solve issue only by removing failed hosts from database.
vpoller-worker --version
0.6.1

**Comment by dnaeon** [comment] 2016-06-23 09:52
Are you using vPoller to monitor directly ESXi hosts or is vPoller connected to a vCenter?

**Comment by jabalv** [comment] 2016-06-23 11:01
No it is connected to ESXi directly. I'm monitoring ESXi servers directly to avoid single point of failure and avoiding vCenter additional overload.

**Comment by dnaeon** [comment] 2016-06-27 07:13
vPoller was designed to be used with vCenter in mind. Using it directly with ESXi hosts will work most of the time, but there are vPoller methods which will work on vCenters only, while on ESXi hosts they would fail.

If you are getting workers stuck because of dead ESXi hosts, you should consider some HA for the vpoller-workers, e.g. using keepalived or something similar.

**Comment by jabalv** [comment] 2016-06-29 08:45
I still think that vPoller should not crash/stuck if hosts is not reachable? Maybe there could implement some check before creating agents from vconnect-cli side or when connection to hosts is lost, it will not stuck but update/mark host in sqlite db. I think this should be investigated, but I need some time...

**Comment by dnaeon** [comment] 2016-07-01 18:14
Closing this one in favour of #198.

We can track progress of fixing this issue in #198

**Closed by dnaeon** 2016-07-01 18:14 UTC
