### ISSUE TITLE
Vpoller not working on vSphere 6.5

### ISSUE THREAD

**Issue by Lem3xcol** [dnaeon/py-vpoller#223] opened 2017-12-15 17:24 UTC
Marin, Hi

I've been using vpoller for a long time, in several installations, and without problem until now. I'm trying of get data from a vcenter vsphere 6.5. The credentials for this vcenter are as follows:

> $ vconnector-cli get

>+-------------------+--------------------------------+------------------------------------------+-----------------+
| Hostname      | Username                        | Password                                    |   Enabled       |
+============+====================+==========================+===========+
| <IP_Address>  | user@datacenter.local     | only_alpha_numeric_characters |         1            |
+-------------------+--------------------------------+------------------------------------------+-----------------+

As you can see, the hostname is identified by its IP address, the username contains the "@" character, and the password is only formed by numbers and letters, no spaces or special characters. When I try to get data from this vcenter, the following error occurs:

>$ vpoller-client --method datacenter.discover --vsphere-host <IP_Address>

>{"msg": "Task datacenter.discover failed", "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/vpoller/task/decorators.py\", line 55, in wrapper\n    result = fn(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/vpoller/vsphere/tasks.py\", line 944, in datacenter_discover\n    obj_type=pyVmomi.vim.Datacenter\n  File \"/usr/lib/python2.7/site-packages/vpoller/vsphere/tasks.py\", line 65, in _discover_objects\n    view_ref = agent.get_container_view(obj_type=[obj_type])\n  File \"/usr/lib/python2.7/site-packages/vconnector/core.py\", line 347, in get_container_view\n    container = self.si.content.rootFolder\n  File \"/usr/lib/python2.7/site-packages/vconnector/core.py\", line 123, in si\n    self.connect()\n  File \"/usr/lib/python2.7/site-packages/vconnector/core.py\", line 159, in connect\n    sslContext=self.ssl_context,\n  File \"/usr/lib/python2.7/site-packages/pyVim/connect.py\", line 856, in SmartConnect\n    mechanism=mechanism)\n  File \"/usr/lib/python2.7/site-packages/pyVim/connect.py\", line 266, in Connect\n    keyFile, certFile, thumbprint, sslContext, connectionPoolTimeout)\n  File \"/usr/lib/python2.7/site-packages/pyVim/connect.py\", line 390, in __Login\n    x = content.sessionManager.Login(user, pwd, None)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 580, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 386, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 1366, in InvokeMethod\n    raise obj # pylint: disable-msg=E0702\nvim.fault.InvalidLogin: (vim.fault.InvalidLogin) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'Cannot complete login due to an incorrect user name or password.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n}\n", "success": 1}

So, I have checked username and password and both are ok, because I can log in Vcenter using them. I have recorded the username using vconnector-cli in the following ways:

> user@datacenter.local 
"user@datacenter.local"
'user@datacenter.local'
user

and none of the above ways allows me to get data from the Vcenter. 

I have set up these credentials in the default zabbix monitoring vmware method, using the form user@datacenter.local (without quotation marks), and it's working like a charm.

What could be wrong?. I'm using Vpoller 0.6.3. in a Centos 7.4 x64_86 with Python 2.7.5. I installed vpoller using "pip install vpoller", as well as the python dependencies, and no more else. I would like to use Vpoller instead Zabbix feature, because with Vpoller I can edit the discovered hosts.

Thanks for the help

Best regards,

Luis Morales

**Comment by Lem3xcol** [comment] 2017-12-15 21:33
Whoa!...it worked!...What I did? I realized that I have not installed zeromq, and I installed in my server using yum. Despite that, vpoller remained without be able to get data. In a last resort, I rebooted the server, and vpoller started to collect data. Do you have any opinion about that?

**Comment by rockaut** [comment] 2018-01-11 19:05
I also hat that problems with the docker container first. It seems to me that this only happens in the first time after a new connection is added/enabled to the vconnector. After a restart of the container or all proxy/worker it worked like a charm. Before that the connection uses the configured user but another or an incorrectly parsed password.

I will try to reproduce that with the containers. Maybe more a problem of vconnection than vpoller?

**Comment by dnaeon** [comment] 2018-06-28 17:30
I've been testing with vSphere 6.5 and it works fine, so not able to reproduce this. Closing this one for now. If you can provide steps to reproduce feel free to re-open.

**Closed by dnaeon** 2018-06-28 17:30 UTC
