### ISSUE TITLE
Joson value not correct in zabbix 2.4.4 ?

### ISSUE THREAD

**Issue by tnndlbmu** [dnaeon/py-vpoller#131] opened 2015-04-24 09:34 UTC
Hi Marin,
when i used discovery to input the vsphere info into zbx monitor, find that it has json format issues,see the screenshot,
![screenshot](https://cloud.githubusercontent.com/assets/8831381/7316176/56f8e14c-eaa7-11e4-8f9b-eb642d578999.png)
env:
system:centos6.6 x64
zbx server version:2.4.4
$ zabbix_server -V
Zabbix server v2.4.4 (revision 52341) (23 February 2015)
Compilation time: Feb 24 2015 20:50:19
pip output:
$ pip freeze
docopt==0.6.2
meld3==1.0.2
pyvmomi==5.5.0.2014.1.1
PyYAML==3.11
pyzabbix==0.7.3
pyzmq==14.5.0
requests==2.6.0
six==1.9.0
supervisor==3.1.3
tabulate==0.7.5
vconnector==0.3.7
vpoller==0.5.1

**Comment by dnaeon** [comment] 2015-04-24 11:21
@tnndlbmu Could you please run this command send see what the result is?

```bash
$ vpoller-client --method datacenter.discover --vsphere-host <vcenter> --helper vpoller.helpers.zabbix
```

**Comment by tnndlbmu** [comment] 2015-04-26 16:46
Hi Marin,
the result:
{"data": [{"{#VSPHERE.DATACENTER.NAME}": " 上海"}, {"{#VSPHERE.DATACENTER.NAME}": "无锡"}, {"{#VSPHERE.DATACENTER.NAME}": "南京"}, {"{#VSPHERE.DATACENTER.NAME}": "杭州"}, {"{#VSPHERE.DATACENTER.NAME}": "温州"}]}

**Comment by dnaeon** [comment] 2015-04-27 05:39
@tnndlbmu That data looks correct, so I'm guessing that you haven't enabled the vPoller Zabbix helpers.

http://vpoller.readthedocs.org/en/latest/vpoller-zabbix.html#enabling-the-vpoller-helpers-for-zabbix

Please post your `vpoller.conf` file as well.

**Comment by tnndlbmu** [comment] 2015-04-27 06:14
@dnaeon 
output shows below:
[proxy]
frontend     = tcp://*:10123
backend      = tcp://*:10124
mgmt         = tcp://*:9999

[worker]
db           = /var/lib/vconnector/vconnector.db
proxy        = tcp://localhost:10124
mgmt         = tcp://*:10000
helpers      = vpoller.helpers.zabbix, vpoller.helpers.czabbix
tasks        = vpoller.vsphere.tasks

[cache]
enabled      = True
maxsize      = 0
ttl          = 3600

Thanks.

**Comment by dnaeon** [comment] 2015-04-27 06:29
That config file looks correct and also the data returned by vPoller is a valid JSON object.

How about the other discovery rules, do they fail with the same error message?

**Comment by tnndlbmu** [comment] 2015-04-27 07:35
yes, fail with the same error message.

**Comment by dnaeon** [comment] 2015-04-27 07:41
Not really sure why it fails, as everything looks correct. I am not able to reproduce this from my side as well, which makes it harder to further assist you on this issue.

Can you please try renaming these clusters to English letters and see if that fixes it? Other than that I cannot really think of anything else that might be the problem, since your config file and JSON objects appear to be valid.

**Comment by tnndlbmu** [comment] 2015-04-27 07:53
i checked the vpoller-worker.log find an error output:
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html 
InsecureRequestWarning)

**Comment by dnaeon** [comment] 2015-04-27 07:57
That warning is okay, it simply warns you that your vSphere host is using a self-signed certificate.

**Comment by tnndlbmu** [comment] 2015-04-27 13:25
problem solved! 
i fresh installed the VM,used pip install vpoller instead of pip install every applications.
all working fine now,thanks.

**Comment by dnaeon** [comment] 2015-04-27 13:42
@tnndlbmu Glad to hear the issue is fixed now!

**Closed by dnaeon** 2015-04-27 13:42 UTC
